feat: ask to install specific components and/targets

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -4,30 +4,86 @@ script_dir=$(dirname "${BASH_SOURCE[0]}")
 # shellcheck source=/dev/null
 . "$script_dir/exec-env"
 
+ask_user() {
+  local question=$1
+  local default=$2
+  local answer
+
+  if [[ -z $default ]]; then
+    read -r -p "$question [Y/n]" answer
+    case $answer in
+    [nN]) printf "no" ;;
+    *) printf "yes" ;;
+    esac
+  else
+    read -r -p "$question y/n/[$default] " answer
+    printf %s "$answer"
+  fi
+}
+
+read_file() {
+  [[ -f $1 ]] && tr '\n' ' ' <"$1"
+}
+
+get_options() {
+  local option_name="$1"
+  local default_options_file_path="$2"
+  local default_options
+  local options
+
+  default_options=$(read_file "$default_options_file_path")
+  options=$(ask_user "Define specifc $option_name(s) to install?" "$default_options")
+
+  case $options in
+  "yes") read -r -p "Enter $option_name(s) (${option_name}1 ${option_name}2 ...): " options ;;
+  "no") options="" ;;
+  *) printf %s "$options" ;;
+  esac
+}
+
 install_rust() {
-    curl --fail --silent --show-error https://sh.rustup.rs \
-    | sh -s -- -y --no-modify-path --default-toolchain "$ASDF_INSTALL_VERSION" --profile "${ASDF_RUST_PROFILE:-default}"
+  local default_rust_components="${ASDF_RUST_DEFAULT_COMPONENTS_FILE:=$HOME/.default-rust-components}"
+  local default_rust_targets="${ASDF_RUST_DEFAULT_TARGETS_FILE:=$HOME/.default-rust-targets}"
+
+  local components
+  local targets
+  components=$(get_options "component" "$default_rust_components")
+  targets=$(get_options "target" "$default_rust_targets")
+
+  curl --fail --silent --show-error https://sh.rustup.rs |
+    sh -s -- -y --no-modify-path \
+      --component "${components}" \
+      --default-toolchain "$ASDF_INSTALL_VERSION" \
+      --profile "${ASDF_RUST_PROFILE:-default}" \
+      --target "${targets}"
+}
+
+install_cargo_crate() {
+    printf "\nInstalling \033[33m%s\033[39m cargo crate... " "$1"
+    # shellcheck disable=SC2086
+    PATH="$ASDF_INSTALL_PATH/bin:$PATH" cargo install $1 >/dev/null && rc=$? || rc=$?
+
+    [[ $rc -eq 0 ]] && printf "\033[32mSUCCESS\033[39m"
+    printf "\033[31mFAIL\033[39m"
+
 }
 
 install_default_cargo_crates() {
-  local default_cargo_crates="${ASDF_CRATE_DEFAULT_PACKAGES_FILE:=$HOME}/.default-cargo-crates"
+  local default_cargo_crates="${ASDF_CRATE_DEFAULT_PACKAGES_FILE:=$HOME/.default-cargo-crates}"
 
-  if [ ! -f $default_cargo_crates ]; then return; fi
+  [[ ! -f $default_cargo_crates ]] && return
 
-  cat "$default_cargo_crates" | while read -r line; do
-    name=$(echo "$line" | 
-      sed 's|\(.*\) //.*$|\1|' |  # handle comments after crate name
+  while read -r line; do
+    name=$(echo "$line" |
+      sed 's|\(.*\) //.*$|\1|' |      # handle comments after crate name
       sed -E 's|^[[:space:]]*//.*||') # handle full line comments
 
-    if [ -z $name ]; then continue ; fi
-    echo -ne "\nInstalling \033[33m${name}\033[39m cargo crate... "
-    PATH="$ASDF_INSTALL_PATH/bin:$PATH" cargo install $name > /dev/null && rc=$? || rc=$?
-    if [[ $rc -eq 0 ]]; then
-      echo -e "\033[32mSUCCESS\033[39m"
-    else
-      echo -e "\033[31mFAIL\033[39m"
-    fi
-  done
+    [[ -z $name ]] && continue
+    # shellcheck disable=SC2086
+    install_cargo_crate $name
+
+
+  done <"$default_cargo_crates"
 }
 
 install_rust
